# Generated by Django 5.2.6 on 2025-10-01 04:02

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('pages', 'UserProfile')
    
    # Get all users without profiles
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_func(apps, schema_editor):
    # No need to delete profiles when reversing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_func),
    ]
